FROM python:3.11-slim

WORKDIR /app

COPY viz/streamlit_app/requirements.txt ./viz/requirements.txt
RUN pip install --no-cache-dir -r viz/requirements.txt

COPY viz/streamlit_app/ ./viz/streamlit_app/

WORKDIR /app/viz/streamlit_app
EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]